In [11]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [12]:
df = pd.read_csv("../data/Clean_Dataset.csv")

In [ ]:
print(df.head(10))

In [ ]:
print("Nombre de lignes et colonnes :", df.shape)

In [ ]:
df.info()

In [ ]:
print(df.isnull().sum())

In [ ]:
statistics = df.describe()

statistics

In [ ]:
print(df.columns)

In [ ]:
print(df.dtypes)

In [20]:
variable_discrete = [
    'airline',
    'flight',
    'source_city',
    'destination_city',
    'departure_time',
    'stops',
    'arrival_time',
    'class'
]

In [ ]:
for col in variable_discrete:
    print(f"Value counts for {col}:")
    print(df[col].value_counts())
    print("\n")

In [ ]:
#Bar plots for discrete variables
import matplotlib.pyplot as plt
import seaborn as sns

for col in variable_discrete:
    plt.figure(figsize=(10, 5))
    
    sns.countplot(
        data=df,
        x=col,
        order=df[col].value_counts().index
    )
    
    plt.title(f"Répartition de {col}")
    plt.xlabel(col)
    plt.ylabel("Fréquence")
    plt.xticks(rotation=45)
    plt.show()

In [ ]:
#flight représentation graphique des 10 vols les plus fréquents
top_flights = df['flight'].value_counts().head(10)

plt.figure(figsize=(10, 5))

sns.barplot(
    x=top_flights.index,
    y=top_flights.values
)

plt.title("Top 10 des vols les plus fréquents")
plt.xlabel("Flight")
plt.ylabel("Fréquence")
plt.xticks(rotation=45)

plt.show()

In [23]:
variable_continue = [
    'duration',
    'days_left',
    'price'
]

In [ ]:
df[variable_continue].describe()

In [ ]:
#histogrammes pour les variables continues
for col in variable_continue:
    plt.figure(figsize=(8, 5))
    
    sns.histplot(
        data=df,
        x=col,
        kde=True     #Kernel Density Estimate
    )
    
    plt.title(f"Distribution de {col}")
    plt.xlabel(col)
    plt.ylabel("Fréquence")
    plt.show()

In [ ]:
#boxplots pour les variables continues
for col in variable_continue:
    plt.figure(figsize=(8, 3))
    
    sns.boxplot(
        data=df,
        x=col
    )
    
    plt.title(f"Boxplot de {col}")
    plt.xlabel(col)
    plt.show()

In [ ]:
pd.crosstab(df['source_city'],df['destination_city'])

In [ ]:
#scatter plot pour visualiser la relation entre deux variable continues
sns.scatterplot(data=df, x='duration', y='price')

In [ ]:
#airline vs price
plt.figure(figsize=(10, 5))

sns.boxplot(
    data=df,
    x='airline',
    y='price'
)

plt.title("Prix selon la compagnie aérienne")
plt.xlabel("Compagnie aérienne")
plt.ylabel("Prix")
plt.xticks(rotation=45)
plt.show()

In [ ]:
#stops vs price
plt.figure(figsize=(10, 5))
sns.boxplot(
    data=df,
    x='stops',
    y='price'
)
plt.title("Prix selon le nombre d'escales")
plt.xlabel("Nombre d'escales")
plt.ylabel("Prix")
plt.show()

In [ ]:
#departure_time vs price
plt.figure(figsize=(10, 5))
sns.boxplot(
    data=df,
    x='departure_time',
    y='price'
)
plt.title("Prix selon l'heure de départ")   
plt.xlabel("Heure de départ")
plt.ylabel("Prix")
plt.show()

In [ ]:
#class vs price
plt.figure(figsize=(10, 5))
sns.boxplot(
    data=df,
    x='class',
    y='price'
)
plt.title("Prix selon la classe de voyage")
plt.xlabel("Classe de voyage")
plt.ylabel("Prix")
plt.show()

In [ ]:
# days_left vs price
plt.figure(figsize=(10, 5))
sns.lineplot(
    data=df,
    x='days_left',
    y='price'
)
plt.title("Prix selon le nombre de jours restants avant le départ")
plt.xlabel("Nombre de jours restants")
plt.ylabel("Prix")
plt.show()

In [ ]:
# preprocessing part 
#Missing Value 
df.isnull().sum()

In [ ]:
target = 'price'

X = df.drop(columns=['price', 'Unnamed: 0'])
y = df['price']
print(X.columns)
print(y)

In [31]:
#install scikit-learn 
from sklearn.model_selection import train_test_split

In [68]:
#divise data 80% train/20% test 
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
)

In [33]:
print("X_train :", X_train.shape)
print("X_test  :", X_test.shape)
print("y_train :", y_train.shape)
print("y_test  :", y_test.shape)

X_train : (240122, 10)
X_test  : (60031, 10)
y_train : (240122,)
y_test  : (60031,)

In [ ]:
print(y_test)

In [34]:
#use SimpleImputer and StandardScaler
numerical_columns = [
    'duration',
    'days_left'
]

In [35]:
#OrdinalEncoder
ordinal_columns = [
    'stops',
    'class'
]

In [36]:
#OneHotEncoder
categorical_columns = [
    'airline',
    'flight',
    'source_city',
    'destination_city',
    'departure_time',
    'arrival_time'
]

In [37]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder, StandardScaler
from sklearn.pipeline import Pipeline

In [38]:
numerical_transformer = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

In [39]:
ordinal_transformer = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OrdinalEncoder())
])

In [40]:
categorical_transformer = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OneHotEncoder(handle_unknown='ignore'))
])

In [41]:
from sklearn.compose import ColumnTransformer

In [42]:
preprocessor = ColumnTransformer([
    ('num', numerical_transformer, numerical_columns),
    ('ord', ordinal_transformer, ordinal_columns),
    ('cat', categorical_transformer, categorical_columns)
])

In [43]:
X_train_processed = preprocessor.fit_transform(X_train)

X_test_processed = preprocessor.transform(X_test)

In [44]:
print(X_train_processed.shape)
print(X_test_processed.shape)

(240122, 1588)
(60031, 1588)

In [45]:
#reference Model 
from sklearn.dummy import DummyRegressor
model = DummyRegressor(strategy='mean')

In [46]:
# Le preprocessing est intégré dans un Pipeline Scikit-learn.
model_pipeline = Pipeline([
    ('preprocessing', preprocessor),
    ('model', model)
])

In [47]:
#fit 
model_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['duration', 'days_left']),
                                                 ('ord',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OrdinalEncoder())]),
                                                  ['stops', 'class']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['airline', 'flight',
                                                   'source_city',
                                                   'destination_city',
                                                   'departure_time',
                                                   'arrival_time'])])),
                ('model', DummyRegressor())])

In [48]:
#prédiction 
y_pred = model_pipeline.predict(X_test)

print(y_pred)

[20938.80676489 20938.80676489 20938.80676489 ... 20938.80676489
 20938.80676489 20938.80676489]

In [49]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

In [50]:
#Regrission Metrics pour DummyRegressor res
r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print("R² :", r2)
print("MAE :", mae)
print("RMSE :", rmse)

R² : -0.0001181030146073514
MAE : 19687.718723080496
RMSE : 22612.708060816803

In [51]:
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.ensemble import RandomForestRegressor
from sklearn.pipeline import Pipeline

In [52]:
#test Models To make the better choice 
def evaluate_model(model, X_test, y_test):
    y_pred = model.predict(X_test)

    mae = mean_absolute_error(y_test, y_pred)
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    r2 = r2_score(y_test, y_pred)

    return mae, rmse, r2

In [53]:
models = {
    "LinearRegression": LinearRegression(),

    "Ridge_0.1": Ridge(alpha=0.1),
    "Ridge_1": Ridge(alpha=1),
    "Ridge_10": Ridge(alpha=10),
    "Ridge_100": Ridge(alpha=100),

    "RandomForest": RandomForestRegressor(
        n_estimators=10,
    )
}

In [ ]:
results = []

for name, model in models.items():

    pipeline = Pipeline([
        ('preprocessing', preprocessor),
        ('model', model)
    ])

    pipeline.fit(X_train, y_train)

    mae, rmse, r2 = evaluate_model(
        pipeline,
        X_test,
        y_test
    )

    results.append({
        'Model': name,
        'MAE': mae,
        'RMSE': rmse,
        'R²': r2
    })

In [54]:
#transform result of models  as a data frame 
import pandas as pd

results_df = pd.DataFrame(results)

results_df

Empty DataFrame
Columns: []
Index: []

In [55]:
from sklearn.model_selection import cross_validate

In [59]:
#applique cross Validation
cv_results = []

for name, model in models.items():

    pipeline = Pipeline([
        ('preprocessing', preprocessor),
        ('model', model)
    ])

    scores = cross_validate(
        pipeline,
        X_train,
        y_train,
        cv=5,
        scoring=[
            'neg_mean_absolute_error',
            'neg_root_mean_squared_error',
            'r2'
        ]
    )

    mae = -scores['test_neg_mean_absolute_error']
    rmse = -scores['test_neg_root_mean_squared_error']
    r2 = scores['test_r2']

    cv_results.append({
        'Model': name,
        'MAE Mean': mae.mean(),
        'MAE Std': mae.std(),
        'RMSE Mean': rmse.mean(),
        'RMSE Std': rmse.std(),
        'R² Mean': r2.mean(),
        'R² Std': r2.std()
    })

In [57]:
#comparaison Table 
cv_results_df = pd.DataFrame(cv_results)

cv_results_df

Empty DataFrame
Columns: []
Index: []

In [63]:
#choice  RandomForestRegressor  as final modéle  (train model)
from sklearn.ensemble import RandomForestRegressor
from sklearn.pipeline import Pipeline

final_model = RandomForestRegressor(
    n_estimators=10,
    random_state=42
)

final_pipeline = Pipeline([
    ('preprocessing', preprocessor),
    ('model', final_model)
])
final_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['duration', 'days_left']),
                                                 ('ord',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OrdinalEncoder())]),
                                                  ['stops', 'class']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['airline', 'flight',
                                                   'source_city',
                                                   'destination_city',
                                                   'departure_time',
                                                   'arrival_time'])])),
                ('model',
                 RandomForestRegressor(n_estimators=10, random_state=42))])

In [64]:
y_pred = final_pipeline.predict(X_test)

final_mae = mean_absolute_error(y_test, y_pred)
final_rmse = np.sqrt(mean_squared_error(y_test, y_pred))
final_r2 = r2_score(y_test, y_pred)
# print(final_r2)

In [65]:
#generate joblib file 
import joblib
import os

os.makedirs("../artifacts", exist_ok=True)

joblib.dump(
    final_pipeline,
    "../artifacts/flight_price_model.joblib"
)

['../artifacts/flight_price_model.joblib']

In [66]:
loaded_model = joblib.load(
    "../artifacts/flight_price_model.joblib"
)

print(loaded_model)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['duration', 'days_left']),
                                                 ('ord',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OrdinalEncoder())]),
                                                  ['stops', 'class']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['airline', 'flight',
                                                   'source_city',
                                                   'destination_city',
                                                   'departure_time',
                                                   'arrival_time'])])),
                ('model',
                 RandomForestRegressor(n_estimators=10, random_state=42))])

In [ ]:
#test modele befor streamlit 
test_row = X_test.loc[[18888]]

real_price = y_test.loc[18888]

prediction = final_pipeline.predict(test_row)[0]

print("Real price:", real_price)
print("Predicted price:", prediction)

Real price: 4272
Predicted price: 4272.0

In [67]:
#JSON file have information about model 
import json

metadata = {
    "model": "RandomForestRegressor",
    "target": target,
    "features": list(X.columns),

    "numerical_variables": numerical_columns,
    "ordinal_variables": ordinal_columns,
    "categorical_variables": categorical_columns,

    "categories": {
        col: sorted(X[col].unique().tolist())
        for col in ordinal_columns + categorical_columns
        if col != "flight"
    },

    "ranges": {
        col: [
            float(X[col].min()),
            float(X[col].max())
        ]
        for col in numerical_columns
    },

    "train_size": len(X_train),
    "test_size": len(X_test),

    "metrics": {
        "MAE": float(final_mae),
        "RMSE": float(final_rmse),
        "R2": float(final_r2)
    }
}

with open(
    "../artifacts/flight_price_model.meta.json",
    "w",
    encoding="utf-8"
) as f:

    json.dump(metadata, f, indent=4)